service: alexa-radio-nova

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add serverless plugins
plugins:
  localPath: '../.serverless_plugins'
  modules:
    - serverless-webpack
    - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs12.x

  logs:
    restApi: true

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
  stackName: ${self:service}-${self:provider.stage}

  memorySize: 128

  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    ENVIRONMENT: ${self:provider.stage}
    REGION: ${self:provider.region}

functions:
  skillLambda:
    handler: src/handler.handler
    events:
      - alexaSkill
